export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-[#020202] text-white pt-32 pb-20 px-6 font-sans relative overflow-hidden">
      {/* Background Grid */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#ffffff03_1px,transparent_1px),linear-gradient(to_bottom,#ffffff03_1px,transparent_1px)] bg-[size:4rem_4rem] pointer-events-none z-0"></div>

      <div className="max-w-4xl mx-auto relative z-10">
        
        {/* Header Section */}
        <div className="mb-16">
          <div className="w-16 h-1 bg-[#f0c808] mb-8"></div>
          <h1 className="text-5xl md:text-7xl font-black uppercase italic tracking-tighter mb-4">
            Terms of <span className="text-transparent [-webkit-text-stroke:1px_rgba(255,255,255,0.8)]">Service</span>
          </h1>
          <div className="flex gap-4 items-center font-mono text-[10px] uppercase tracking-widest text-zinc-500">
            <span>Effective Date: {new Date().toLocaleDateString()}</span>
            <span className="w-1 h-1 rounded-full bg-zinc-500"></span>
            <span>WearWhatever.in</span>
          </div>
        </div>

        {/* Legal Content */}
        <div className="space-y-12 text-zinc-300 text-sm md:text-base leading-relaxed font-mono">
          
          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 border-b border-white/10 pb-4">1. Overview & Acceptance</h2>
            <div className="space-y-4 text-zinc-400">
              <p>This website is operated by <strong className="text-white">RUDRANSH GARG</strong> (Founder & Developer). Throughout the site, the terms "we", "us" and "our" refer to Wear Whatever. Wear Whatever offers this website, including all information, tools, AI generation services, and products available from this site to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here.</p>
              <p>By visiting our site and/or purchasing something from us, you engage in our "Service" and agree to be bound by the following terms and conditions ("Terms of Service", "Terms"). These Terms of Service apply to all users of the site, including without limitation users who are browsers, vendors, customers, merchants, and/or contributors of content.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 border-b border-white/10 pb-4">2. The AI Design Studio & Intellectual Property</h2>
            <div className="space-y-4 text-zinc-400">
              <p>Wear Whatever utilizes advanced Artificial Intelligence (AI) to allow users to generate custom graphics for apparel. By utilizing our AI Studio, you strictly agree to the following:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li><strong className="text-white">Prohibited Prompts:</strong> You will not input prompts designed to generate hate speech, explicit sexual content, realistic depictions of minors, or excessively violent imagery.</li>
                <li><strong className="text-white">Copyright Infringement:</strong> You will not use the AI Studio to generate and purchase direct replicas of existing trademarked logos, copyrighted characters, or intellectual property belonging to third parties (e.g., Disney, Nike, Supreme). You assume all legal liability for copyright infringement resulting from your specific prompts.</li>
                <li><strong className="text-white">Commercial Rights:</strong> The unique images generated by the AI on our platform remain the intellectual property of Wear Whatever. By finalizing a purchase, you are granted a physical realization of the design, but you do not own the exclusive digital copyright to the generated image. We reserve the right to display, market, or resell generated designs.</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 border-b border-white/10 pb-4">3. Custom 1-of-1 Products</h2>
            <div className="space-y-4 text-zinc-400">
              <p>Because every garment is manufactured on-demand specifically based on your unique AI-generated prompt, <strong>all sales are final.</strong> We do not hold inventory of your specific design.</p>
              <p>We have made every effort to display as accurately as possible the colors and images of our products that appear at the store. However, because AI generation is a digital process (RGB) and physical printing utilizes ink (CMYK), slight color variations and fabric texture adaptations are expected and do not classify as a "defect."</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 border-b border-white/10 pb-4">4. Accuracy of Billing and Account Information</h2>
            <div className="space-y-4 text-zinc-400">
              <p>We reserve the right to refuse any order you place with us. We may, in our sole discretion, limit or cancel quantities purchased per person, per household or per order. In the event that we make a change to or cancel an order, we may attempt to notify you by contacting the e-mail and/or billing address/phone number provided at the time the order was made.</p>
              <p>You agree to provide current, complete and accurate purchase and account information for all purchases made at our store.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 border-b border-white/10 pb-4">5. Prohibited Uses</h2>
            <div className="space-y-4 text-zinc-400">
              <p>In addition to other prohibitions as set forth in the Terms of Service, you are prohibited from using the site or its content:</p>
              <ol className="list-[lower-alpha] pl-5 space-y-2">
                <li>for any unlawful purpose;</li>
                <li>to solicit others to perform or participate in any unlawful acts;</li>
                <li>to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances;</li>
                <li>to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability;</li>
                <li>to upload or transmit viruses, malicous code, or attempt to reverse-engineer our AI generation pipeline or backend architecture.</li>
              </ol>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 border-b border-white/10 pb-4">6. Disclaimer of Warranties; Limitation of Liability</h2>
            <div className="space-y-4 text-zinc-400">
              <p>We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free. We do not warrant that the results that may be obtained from the use of the service (specifically the AI image generator) will always meet your exact subjective expectations.</p>
              <p>In no case shall Wear Whatever, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 border-b border-white/10 pb-4">7. Indemnification</h2>
            <div className="space-y-4 text-zinc-400">
              <p>You agree to indemnify, defend and hold harmless Wear Whatever and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys’ fees, made by any third-party due to or arising out of your breach of these Terms of Service or the documents they incorporate by reference, or your violation of any law or the rights of a third-party (specifically including copyright infringement resulting from your AI text prompts).</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 border-b border-white/10 pb-4">8. Governing Law</h2>
            <div className="space-y-4 text-zinc-400">
              <p>These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of India, and jurisdiction shall fall strictly under the courts of Uttar Pradesh, India.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white uppercase tracking-wider mb-4 border-b border-white/10 pb-4">9. Contact Information</h2>
            <div className="space-y-4 text-zinc-400">
              <p>Questions about the Terms of Service should be sent to us at:</p>
              <div className="bg-zinc-950 border border-white/10 p-4 inline-block mt-2">
                <p className="font-bold text-white">Wear Whatever Legal Division</p>
                <p>Email: support.wearwhatever@gmail.com</p>
                <p>Support: support.wearwhatever@gmail.com</p>
              </div>
            </div>
          </section>

        </div>
      </div>
    </main>
  );
}